apiVersion: apps/v1
kind: Deployment
metadata:
  name: fourthcoffee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fourthcoffee-app
  template:
    metadata:
      labels:
        app: fourthcoffee-app
    spec:
      containers:
      - name: fourthcoffee
        image: bcacr.azurecr.io/fourthcoffeepos:latest
        ports:
        - containerPort: 5000
        env:
        - name: DBHOST
          value: my-db
        - name: DBNAME
          value: fourthcoffee
        - name: DBUSER
          value: root
        - name: DBSECRET
          value: secret
---
apiVersion: v1
kind: Service
metadata:
  name: fourthcoffee-app
  labels:
    app: fourthcoffee-app
spec:
  type: LoadBalancer
  selector:
    app: fourthcoffee-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        env:
        - name: MYSQL_DATABASE
          value: fourthcoffee
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: my-db
spec:
  selector:
    app: my-db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
